# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=128)),
                ('team_id', models.CharField(max_length=16)),
                ('team_name', models.CharField(max_length=128)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('last_sync_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'teamsync_group',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_member_name', models.CharField(max_length=64, unique=True)),
                ('github_username', models.CharField(max_length=64, unique=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'teamsync_user',
            },
        ),
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('group_id', 'team_id')]),
        ),
    ]
