# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsync', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
        migrations.AlterField(
            model_name='group',
            name='team_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
