# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsync', '0002_auto_20161117_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_member_name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
